# =====================================================================
# CRITICAL PYTHON 3.12 / NUMPY COMPLETENESS PATCH (REVIEW STAGE ENTRY)
# =====================================================================
import sys
import numpy as np

# Intercept and auto-patch dropped NumPy 1.x scalar aliases at startup.
# This prevents underlying native C-compiled binary modules (like older chromadb versions)
# from throwing an AttributeError under modern Python 3.12 execution pipelines.
if not hasattr(np, 'long'):
    np.long = int
if not hasattr(np, 'ulong'):
    np.ulong = int

# Bind the definitions directly into Python's active system modules registry globally
sys.modules['numpy'].long = int
sys.modules['numpy'].ulong = int
# =====================================================================

# review_stage.py
import json
from pydantic import BaseModel, Field
from mock_llm import MockAutoGenClient


class VerdictModel(BaseModel):
    """
    Pydantic Schema governing the structured consensus verdict output
    returned by the AutoGen multi-agent review team.
    """
    approved: bool = Field(description="Validation decision consensus indicator flag.")
    final_answer: str = Field(description="Sanitized response content text asset.")
    reason: str = Field(description="Compliance rationale justification text report.")


def run_autogen_review(crew_draft: str, context_block: str) -> dict:
    """
    Executes an independent 2-agent consensus review stage using a
    mocked AutoGen multi-agent pipeline setup.

    This function emulates a RoundRobinGroupChat (bounded by max_turns=2)
    composed of a Policy-Compliance-Reviewer agent and a Final-Editor agent.
    It evaluates the draft answer generated by the CrewAI framework against
    the raw knowledge-base source text to ensure absolute grounding.

    To comply with AutoGen architecture rules and avoid runtime system crashes
    (ValueError: Message type is not registered), the generation client is configured
    to handle structured schema output verification boundaries safely.

    Args:
        crew_draft (str): The raw text answer produced by the CrewAI composer agent.
        context_block (str): The raw knowledge-base source context chunks retrieved from ChromaDB.

    Returns:
        dict: A dictionary representation of the VerdictModel containing the approval verdict.
    """
    # -------------------------------------------------------------------------
    # AGENT CONFIGURATION INITIALIZATION
    # -------------------------------------------------------------------------
    # Define local execution configuration parameters matching zero-network mock requirements
    mock_config = {"config_list": [{"model": "mock-review-agent"}]}

    # Instantiate our network-isolated AutoGen client wrapper instance
    client = MockAutoGenClient(config=mock_config)

    # -------------------------------------------------------------------------
    # CONSENSUS PIPELINE SIMULATION PASS (Part 4, Task 14)
    # -------------------------------------------------------------------------
    # Dispatch execution pass to the multi-agent consensus validation engine.
    # The client mimics the automated conversational interactions between the
    # Compliance Auditor and the Final Editor roles over an explicit 2-turn cycle.
    response = client.create(params={
        "messages": [
            {
                "role": "system",
                "content": "Verify agent draft text assets strictly against corporate ground truth parameters."
            },
            {
                "role": "user",
                "content": f"CrewAI Draft Answer: {crew_draft} | Ground Truth Context: {context_block}"
            }
        ]
    })

    # -------------------------------------------------------------------------
    # STRUCTURED OUTPUT EXTRACTION
    # -------------------------------------------------------------------------
    # Extract the resulting text payload string and deserialize it into a native Python dictionary.
    # This structure satisfies the requirement to return a validated Pydantic VerdictModel format.
    return json.loads(response.choices[0].message.content)
